#
# SPI
#

CONFIG_SPI=y

#
# USB / central
#

CONFIG_ZMK_USB=y

#
# USB runtime logging
#

CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL=4

#
# External power
#
# Внешний power switch не используется.
#

CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
