#
# SPI
#

CONFIG_SPI=y

#
# USB
#
# Правая половина используется как central.
# USB включаем только здесь, а не в общем charybdis.conf.
#

CONFIG_ZMK_USB=y

#
# External power
#

CONFIG_ZMK_EXT_POWER=y
