#
# SPI
#

CONFIG_SPI=y

#
# USB
#

CONFIG_ZMK_USB=y

#
# External power
#
# Внешний power switch не используется,
# поэтому отключаем его.
#

CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
