#
# Bluetooth connection parameters
#

CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y

# Минимальный интервал соединения:
# 6 * 1.25 ms = 7.5 ms
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6

# Максимальный интервал соединения:
# 9 * 1.25 ms = 11.25 ms
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9

# Peripheral не пропускает connection events
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Timeout:
# 400 * 10 ms = 4000 ms
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

#
# Bluetooth power
#

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#
# Battery
#

CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

#
# 32 kHz crystal
#

CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

#
# Pointing device / PMW3610
#

CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_INPUT_PMW3610=y

#
# RGB underglow
#

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_LED_STRIP=y

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=6

CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

#
# RGB startup parameters
#

CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3

#
# ZMK Studio
#

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
