manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: podkolodnyi
      url-base: https://github.com/podkolodnyi

  projects:
    - name: zmk
      remote: podkolodnyi
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: podkolodnyi
      revision: main
      
  self:
    path: config
